"""
Garment, GarmentVersion, and GarmentFile models.
The Garment is the core entity — identified by its UGI.
"""
import enum
from datetime import datetime

from sqlalchemy import DateTime, Enum, Float, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.database import Base


class GarmentStatus(str, enum.Enum):
    DRAFT = "draft"
    PROCESSING = "processing"
    ACTIVE = "active"
    UPDATING = "updating"   # Active garment being re-processed
    ERROR = "error"         # Pipeline failed — human intervention needed
    ARCHIVED = "archived"
    DELETED = "deleted"     # Soft-deleted, excluded from all queries by default


class GarmentCategory(str, enum.Enum):
    TOPS = "tops"
    BOTTOMS = "bottoms"
    DRESSES = "dresses"
    OUTERWEAR = "outerwear"
    SUITS = "suits"         # Added to match shared/types.ts and web types
    UNDERWEAR = "underwear"
    SWIMWEAR = "swimwear"
    ACTIVEWEAR = "activewear"
    FOOTWEAR = "footwear"
    ACCESSORIES = "accessories"
    BAGS = "bags"
    HATS = "hats"
    OTHER = "other"


# Category code mapping for UGI generation
CATEGORY_CODES: dict[str, str] = {
    GarmentCategory.TOPS: "TO",
    GarmentCategory.BOTTOMS: "BT",
    GarmentCategory.DRESSES: "DR",
    GarmentCategory.OUTERWEAR: "OW",
    GarmentCategory.SUITS: "SU",
    GarmentCategory.UNDERWEAR: "UW",
    GarmentCategory.SWIMWEAR: "SW",
    GarmentCategory.ACTIVEWEAR: "AW",
    GarmentCategory.FOOTWEAR: "FW",
    GarmentCategory.ACCESSORIES: "AC",
    GarmentCategory.BAGS: "BG",
    GarmentCategory.HATS: "HT",
    GarmentCategory.OTHER: "OT",
}

CATEGORY_CODE_REVERSE: dict[str, str] = {v: k for k, v in CATEGORY_CODES.items()}


class GarmentFileType(str, enum.Enum):
    PHOTO = "photo"
    VIDEO = "video"
    PATTERN_AI = "pattern_ai"
    PATTERN_DXF = "pattern_dxf"
    CLO3D = "clo3d"
    MARVELOUS = "marvelous"
    MODEL_3D = "model_3d"
    TECH_PACK = "tech_pack"
    OTHER = "other"


class Garment(Base):
    __tablename__ = "garments"

    # UGI is the primary key — generated by UGI service, not UUID4
    id: Mapped[str] = mapped_column(String(50), primary_key=True, index=True)
    brand_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), ForeignKey("brands.id", ondelete="RESTRICT"), nullable=False, index=True
    )
    status: Mapped[GarmentStatus] = mapped_column(
        Enum(GarmentStatus), default=GarmentStatus.DRAFT, nullable=False, index=True
    )
    category: Mapped[GarmentCategory] = mapped_column(
        Enum(GarmentCategory), nullable=False, index=True
    )
    name: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    sku: Mapped[str | None] = mapped_column(String(200), index=True)
    fabric_physics_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False), ForeignKey("fabric_physics.id", ondelete="SET NULL"), index=True
    )
    # Extensible brand-specific metadata
    metadata_: Mapped[dict] = mapped_column("metadata", JSONB, default=dict, nullable=False)
    # EU Digital Product Passport fields
    dpp_data: Mapped[dict] = mapped_column(JSONB, default=dict, nullable=False)
    # Size chart — multiple sizes supported
    size_chart: Mapped[dict] = mapped_column(JSONB, default=dict, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # Relationships
    brand: Mapped["Brand"] = relationship("Brand", back_populates="garments")  # noqa: F821
    versions: Mapped[list["GarmentVersion"]] = relationship(
        "GarmentVersion", back_populates="garment", order_by="GarmentVersion.version_number.desc()"
    )
    files: Mapped[list["GarmentFile"]] = relationship(
        "GarmentFile", back_populates="garment"
    )
    fabric_physics: Mapped["FabricPhysics | None"] = relationship(  # noqa: F821
        "FabricPhysics", foreign_keys=[fabric_physics_id]
    )
    try_ons: Mapped[list["TryOn"]] = relationship("TryOn", back_populates="garment")  # noqa: F821

    def __repr__(self) -> str:
        return f"<Garment {self.id}: {self.name}>"


class GarmentVersion(Base):
    """Immutable audit trail of every change to a garment."""
    __tablename__ = "garment_versions"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(__import__("uuid").uuid4())
    )
    garment_id: Mapped[str] = mapped_column(
        String(50), ForeignKey("garments.id", ondelete="CASCADE"), nullable=False, index=True
    )
    version_number: Mapped[int] = mapped_column(Integer, nullable=False)
    changed_by: Mapped[str | None] = mapped_column(String(255))  # user_id or "system"
    change_type: Mapped[str] = mapped_column(String(50), nullable=False)  # update, status_change, etc.
    diff: Mapped[dict] = mapped_column(JSONB, default=dict, nullable=False)  # Before/after diff
    snapshot: Mapped[dict] = mapped_column(JSONB, default=dict, nullable=False)  # Full garment snapshot
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    garment: Mapped["Garment"] = relationship("Garment", back_populates="versions")

    def __repr__(self) -> str:
        return f"<GarmentVersion {self.garment_id} v{self.version_number}>"


class GarmentFile(Base):
    """Files associated with a garment — photos, patterns, 3D models, etc."""
    __tablename__ = "garment_files"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(__import__("uuid").uuid4())
    )
    garment_id: Mapped[str] = mapped_column(
        String(50), ForeignKey("garments.id", ondelete="CASCADE"), nullable=False, index=True
    )
    file_type: Mapped[GarmentFileType] = mapped_column(
        Enum(GarmentFileType), nullable=False, index=True
    )
    original_filename: Mapped[str] = mapped_column(String(500), nullable=False)
    storage_key: Mapped[str] = mapped_column(String(1000), nullable=False)  # S3/GCS key
    storage_url: Mapped[str | None] = mapped_column(String(2000))  # Public URL if applicable
    mime_type: Mapped[str] = mapped_column(String(100), nullable=False)
    file_size_bytes: Mapped[int] = mapped_column(Integer, nullable=False)
    width_px: Mapped[int | None] = mapped_column(Integer)  # For images
    height_px: Mapped[int | None] = mapped_column(Integer)  # For images
    duration_seconds: Mapped[float | None] = mapped_column(Float)  # For videos
    is_primary: Mapped[bool] = mapped_column(default=False, nullable=False)
    processing_status: Mapped[str] = mapped_column(
        String(50), default="pending", nullable=False
    )  # pending, processing, complete, failed
    processing_metadata: Mapped[dict] = mapped_column(JSONB, default=dict, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    garment: Mapped["Garment"] = relationship("Garment", back_populates="files")

    def __repr__(self) -> str:
        return f"<GarmentFile {self.file_type.value}: {self.original_filename}>"
